config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :appointments

  root "pages#index"

  get '/gallery' => 'pages#gallery'
  get '/classroom' => 'pages#classroom'
  get '/on_boat' => 'pages#on_boat'
  get '/delivery' => 'pages#delivery'
  get '/prepurchase' => 'pages#prepurchase'
  get '/decommissioning' => 'pages#decommissioning'
  get '/recommissioning' => 'pages#recommissioning'
  get '/about' => 'pages#about'
end

  #   end

app/models/appointment.rb
class Appointment < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: {case_sensitive: false }
										
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def index
		@appointment = Appointment.all
	end

	def new
		@appointment = Appointment.new
	end

	def set_hours(start_time, end_time)
		#this method will create an array of the total number of hours for the day selected
		#each index in the array will a new row in the Appointment database

		#determine how many elements will be in the array
		total_hours = (end_time.to_i) - (start_time.to_i)
		hours = Array.new(total_hours)
		
		#starting with start_time, add an hour for each element in the array		
		hours.each_index do |i|
			hours[i] = ((params[:appointment][:start_time]).to_i) + i
		end
		return hours
	end

	def create
		params.require(:appointment).permit(:appt_date, :start_time, :end_time)

		#send the values from the form to the set_hours method
		new_rows = set_hours(params[:appointment][:start_time], params[:appointment][:end_time])

		#create a new row in the database for each element in the array
		0.upto(new_rows.length-1) do |i|
			a = Appointment.new
			a.appt_date = params[:appointment][:appt_date]
			a.start_time = new_rows[i]
			a.end_time = new_rows[i] + 1
			a.reserved = false
			#binding.pry
			a.save
		end

		#Put a flash here for success message

		redirect_to appointments_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		# Log the user in and redirect back to home page with the create new appt shown
  		log_in user
  		redirect_to root_path
  	else
  		# Create an error message
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user
	def log_in(user)
		session[:user_id] = user.id		
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
  	@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/appointments/index.html.erb
<div id='calendar'></div>



<!--
<% @appointment.group_by(&:appt_date).each do |date, appt| %>
	<tr> <td colspan="7"> <h1><%= date %></h1> </td> </tr>
	<h3>Appointments:</h1>
	<% appt.each do |appt|  %>
		<tr>
			<td>Time: <%= appt.start_time %> - <%= appt.end_time %></td>
		</tr><br>
	<% end  %>
<% end %>

app/views/appointments/new.html.erb
<!-- A form will be on this page for start time and end time
	Subtract the end time from the start time to get the total amount of hours desired
	Create a new row in the Appointments database for each hour
	IE start time is 08:00 and end time is 17:00, so 9 hour work day, 9 rows in the db for that day
-->



<%= form_for @appointment do |f| %>
	<p>
		<%= f.label :date %>
		<%= f.text_field :appt_date %>
	</p>

	<p>
		<%= f.label :start_time %>
		<%= f.time_field :start_time, step: 3600 %>
	</p>

	<p>
		<%= f.label :end_time %>
		<%= f.time_field :end_time, step: 3600 %>
	</p>

	<p><%= f.submit %></p>
<% end %>

app/views/calendar/index.html.erb
<div id='calendar'></div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="container text-center">
    <p class="text-muted">Admin Login</p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand" ><%= link_to "Cape Cod Captains", root_path %>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "Gallery", gallery_path %></li>
        <li><%= link_to "Delivery", delivery_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Instruction<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Classroom", classroom_path %></li>
            <li><%= link_to "On Your Boat", on_boat_path %></li>         
          </ul> 
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Inspection<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Prepurchase", prepurchase_path %></li>
            <li><%= link_to "Decommissioning", decommissioning_path %></li>
            <li><%= link_to "Recommissioning", recommissioning_path %></li>       
          </ul> 
        </li>
        <% if logged_in? %>
        <li><%= link_to "Schedule", root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <l1><%= link_to "Sign Out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", login_path %></li>
          <li><%= link_to "Sign Up", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JeffWebsite</title>

  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

      <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <!-- Custom style for footer -->
     <link href="sticky-footer.css" rel="stylesheet">

  <!--[if IE]>
<style type="text/css">
#content,
#main,
#inner-wrap,
#wrap {
zoom:1;
}
</style>
<![endif]-->

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
<script src='lib/jquery.min.js'></script>
<script src='lib/moment.min.js'></script>
<script src='fullcalendar/fullcalendar.js'></script>

</head>
<body>

  <div class='container-fluid'>
    <%= render "layouts/navigation" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%=message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>
  <%= render "layouts/footer" %>

</body>

<!-- for dateTimePicker -->
<link rel="stylesheet" type="text/css" href="jquery.datetimepicker.css"/ >
<script src="jquery.js"></script>
<script src="jquery.datetimepicker.js"></script>

</html>

app/views/pages/classroom.erb
<h1>Learn in the classroom</h1>

<a href='classroom_schedule_appointment' type="button" class="btn btn-default">Schedule Class</a>

app/views/pages/delivery.html.erb
<h1>Delivery</h1>

app/views/pages/gallery.html.erb
<h1>Gallery</h1>

app/views/pages/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
	  <div class="container">
	    <h1>Captain Jeffrey Fryar</h1>
	    <p>Captain Fryar is a USCG approved instructor for Launch, OUPV (6 pack)
	    	and 100 Ton Master.</p>
	    <p><a class="btn btn-lg btn-primary" href="" role="button">Learn More &raquo;</a></p>
	  </div>
	</div>

app/views/pages/learn_in_the_classroom.erb
<h1>Learn in the classroom</h1>

<a href='classroom_schedule_appointment' type="button" class="btn btn-default">Schedule Class</a>

app/views/pages/learn_in_the_field.html.erb
<h1>Learn on Your Boat</h1>

app/views/pages/on_boat.html.erb
<h1>Learn on Your Boat</h1>